yatube/about/urls.py
# файл about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/',
         views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/',
         views.AboutTechView.as_view(),
         name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Отдельная страница групп
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание и редактирование записи
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logged_out.html'),
        name='logout'),
    path('password_change_done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done',),
    path('password_change_form/', auth_views.PasswordChangeView.as_view(
         template_name='users/password_change_form.html'),
         name='password_change_form',),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'),
         name='password_reset_done',),
    path('password_reset_form/', auth_views.PasswordResetView.as_view(
         template_name='users/password_reset_form.html'),
         name='password_reset_form',),
    path('password_reset_confirm/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm',),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'posts'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=200,
        help_text='Введите заголовок поста'
    )
    slug = models.SlugField(
        'Адрес страницы группы',
        unique=True)
    description = models.TextField(
        'Описание',
        help_text='Введите описание группы'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Group'


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='group_posts',
        verbose_name='Автор')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='group_posts',
        blank=True, null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        verbose_name = 'Post'
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Post

User = get_user_model()


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group',)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User


@require_http_methods(["GET"])
def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {'page_obj': page_obj, }
    return render(request, template, context)


@require_http_methods(["GET"])
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@require_http_methods(["GET"])
def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    posts = author.group_posts.all()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    context = {
        'page_obj': page_obj,
        'author': author,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    count = Post.objects.filter(author=post.author).count()
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'count': count,
    }
    return render(request, template, context)


@login_required
@require_http_methods(["GET", "POST"])
def post_create(request):
    groups = Group.objects.all()
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author.username)
    else:
        print(form.errors)
    template = 'posts/create_post.html'
    return render(request, template, {'form': form, 'groups': groups})


@login_required
@require_http_methods(["GET", "POST"])
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        template = 'posts:post_detail'
        post.save()
        return redirect(template, post_id=post.pk)
    groups = Group.objects.all()
    template = 'posts/create_post.html'
    context = {
        'form': form,
        'groups': groups,
        'is_edit': is_edit
    }
    return render(request, template, context)

yatube/users/views.py
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class LoginView(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/login.html'


class PasswordReset(PasswordResetView):
    form_class = PasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    template_name = 'users/password_reset_form.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Привет, я автор</h1>
  <article>
    <ul>
      <li>
        <p>
          Меня зовут Лера Невская.
        </p>
        <p> 
          Я была учителем, но решила попробовать что-то новое. Надеюсь, все получится! 
        </p>
        
      </li>
    </ul>
  </article>
</div>  
{% load static %}
<img src="{% static 'img/me.png' %}" width="300" height="200" class="d-inline-block align-top" alt="">
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
        {% load static %}
        <img src="{% static 'img/python.png' %}" width="350" height="200" class="d-inline-block align-top" alt="">
      </li>
      <li class="list-group-item">
        Django
        {% load static %}
        <img src="{% static 'img/django.png' %}" width="350" height="200" class="d-inline-block align-top" alt="">
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Это те технологии, которые я изучаю в Яндекс.Практикуме</p>
  </article>
</div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">  
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">    
    <title>
      {% block title %}
        Главная страница
      {% endblock %}
    </title>     
  </head>
  <body>       
    <header>
      {% include "includes/header.html" %}
    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include "includes/footer.html" %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<nav class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
    </div>
</nav>

yatube/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        {% load static %}
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {# Добавлено в спринте 4#}
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %} 
      <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">
        <a class="nav-link 
        {% if view_name  == 'about:author' %} active {% endif %}" 
        href="{% url 'about:author' %}"> Об авторе </a>
      </li>
      <li class="nav-item">
        <a class="nav-link 
        {% if view_name  == 'about:tech' %} active {% endif %}" 
        href="{% url 'about:tech' %}"> Технологии </a>
      </li>
        <!-- Проверка: авторизован ли пользователь? -->
        {% if user.is_authenticated %}
          <li>
            Пользователь: {{ user.username }}
          <li>
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name == 'posts:post_create' %} active {% endif%}"
            href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link 
            {% if view_name  == 'users:password_change_form' %} active {% endif %}"
            href="{% url 'users:password_change_form' %}"> Изменить пароль </a>
          </li>
          <li class="nav-item">
            <a class="nav-link 
            {% if view_name  == 'users:logout' %} active {% endif %}" 
            href="{% url 'users:logout' %}"> Выйти </a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link 
            {% if view_name  == 'users:login' %} active {% endif %}" 
            href="{% url 'users:login' %}"> Войти </a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link 
            {% if view_name  == 'users:signup' %} active {% endif %}" 
            href="{% url 'users:signup' %}"> Регистрация </a>
          </li>
        {% endif %}
      {% endwith %}
      </ul>
      {# Конец добавленого в спринте 4#}
    </div>
  </nav>      
</header>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
Новый пост
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}                     
              </div>
              <div class="card-body">    
                
                {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
                
                <form method="post" href="{% url 'posts:post_create' %}">
                  {% csrf_token %} 

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      {% for group in groups %}
                        <option value="{{ group.pk }}"selected>{{ group.title }} </option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
{{group.title}}
{% endblock %}
{% block content %}
<div class="container py-5">
  Записи сообщества <h1>{{ group.title }}</h1>
    <p> {{ group.description }}</p>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>
    {% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
</div>  
{% endblock %}    

yatube/templates/posts/includes/paginator.html
{# templates/posts/includes/paginator.html #}

    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}    
      </ul>
    </nav>
    {% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Это главная страница проекта Yatube
{% endblock %}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author }}
      </li>
      <a href="{% url "posts:profile" username=post.author%}">все посты пользователя</a>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    <p><a href="{% url "posts:post_detail" post.pk %}">подробная информация </a></p>
    {% if post.group %} <a href="{% url "posts:group_list" post.group.slug %}">все записи группы</a> 
    {% endif %}
    {% if not forloop.last %}<hr>
    {% endif %}
    
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  <!-- под последним постом нет линии -->
  </article>
</div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
Пост
{{post.text|truncatechars:30}}
{% endblock %}
{% block content %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            <!-- если у поста есть группа -->   
                {% if post.group %}
                <li class="list-group-item">
                  Группа: {{group}}
                
                <p><a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы </a></p>        
                {% endif %}
                </li>
              <li class="list-group-item">
                Автор: {{ post.author }} 
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ count }}</span>
              </li>
              <li class="list-group-item">
              <p><a href="{% url "posts:profile" username=post.author%}">все посты пользователя</a></p> 
              </li> 
          </ul>
        </aside>
        
      </div>
        <li class="list-group-item">
          {{post.text}}
        
    <a class="btn btn-primary" href={% url 'posts:post_edit' post_id=post.pk%}>
      редактировать запись
    </a>
        </li>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профайл пользователя {{author}}
{% endblock %}
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ posts.count }} </h3>   
      <article>
      {% for post in page_obj %}
        <ul>
          <li>
          Автор: {{ post.author }}
          </li>
          <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          </ul>
          <p>{{ post.text|truncatewords:10 }}</p>
          <a href="{% url "posts:post_detail" post.pk %}">подробная информация </a>
          <!-- Остальные посты. после последнего нет черты -->
          {% if post.group %}
            <p><a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы </a></p>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
        <!-- Здесь подключён паджинатор -->  
      {% include 'posts/includes/paginator.html' %}
      </article>  
</div>
{% endblock %}

yatube/templates/posts/update_post.html
{% extends 'base.html' %}
{% block title %}
Редактировать пост
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" href="{% url 'posts:post_edit' %}">
                  {% csrf_token %}                        
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" >---------</option>
                      {% for group in groups %}
                        <option value="{{ group.pk }}">{{ group.title }} </option>
                      {% endfor %}
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}
Войти
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Войти на сайт
              </div>
              <div class="card-body">
                <form method="post" {% url 'users:login' %}>
                  {% csrf_token %}
                  <div class="form-group row my-3">
                    <label for="id_username">
                      Имя пользователя
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="text" name="username" autofocus class="form-control" required id="id_username">
                  </div>
                  <div class="form-group row my-3">
                    <label for="id_password">
                      Пароль
                      <span class="required text-danger">*</span>
                    </label>
                    <input type="password" name="password" class="form-control" required id="id_password">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Войти
                    </button>
                    <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                      Забыли пароль?
                    </a>
                  </div>
                </form>
              </div> 
            </div> 
          </div>
        </div>
      </div>
    </main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}
Сброс пароля
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" {% url 'users:password_reset_form' %}>
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% include 'posts/includes/paginator.html' %}
{% endblock %}